### ISSUE TITLE
Add a prefix option

### ISSUE THREAD

**Issue by kvoon3** [antfu/vscode-ext-gen#1]
### Clear and concise description of the problem

According to the current codebase, when generating scoped configs, we need to trim off the extension prefix, and our extension prefix is hardcoded as the package name. However, in some case, the package name may not always match the extension name.

For example, when we fork a VSCode extension and prepare to publish it to the marketplace, according to VSCode Marketplace restrictions, the extension's name (package.json -> name) must be unique. Despite this, we still want to keep using the previous prefix:

```jsonc
{
  // package.json
  "name": "iconify-my-fork",
  "contributes": {
    "configuration": {
      "properties": {
        "iconify.inplace": {
            //...
        }
      }
    }
  }
}
```

Since the name become `iconify-my-fork`, when generating scoped configs, `iconify.inplace` would be filtered out because its prefix does not match `iconify-my-fork`.

### Suggested solution

Add a prefix option in cli that defaults to package name, and i will try to submit a PR later.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds reasonable, looking forward to your PR!
